### ISSUE TITLE
[BUG] Get 404 when user by ID is not found

### ISSUE THREAD

**Issue by z-rayc** [nokacper24/group4webshop#76]
**Problem**
When a user with a specific ID is not found, the error 'Internal Server Error' is returned. This does not represent the problem accurately enough.

**Solution**
When the database is unable to find the user, return a 404 Not Found instead.

**Comment by JakobHolkestadMolnes** [comment]
fixed in 579faed2a1d8512cb7a7cb956fb7bd8ecdf47187
And merged in bf860670bf69feb7ab5f45bfd1ec125df9cbda87
