### ISSUE TITLE
[FEATURE REQUEST] email invite generation separation

### ISSUE THREAD

**Issue by nokacper24** [nokacper24/group4webshop#83]
**Idea**  
I think we should separate *new user* invite endpoint and *company user* invite endpoint.  
This way we can separate responsibilities and auth required for these.  

Responsibilities:  
- **new user**: create new user along with a company
- **new company user**: create a new user tied to the company associated with the invite-endpoint caller.

Auth:
- **new user**: no authentication required - *anyone* can register themselves + their company
- **new company user**: requires auth, caller must be companyit/companyithead (check if the company they are inviting to is the company they belong to!!!!) or admin (can invite to any valid company)

**Comment by nokacper24** [comment]
> - new company user: create a new user tied to the company associated with the invite-endpoint

include company name in the payload maybe, and then check if caller's company = company in payload? (if not, **forbidden**)
This way **admin** can generate invite to any company, does not need to be a part of it.

**Comment by JakobHolkestadMolnes** [comment]
should be possible if I add company as an Option to the Invite struct mby? and then just check against that in the match statement
